name: RealShop
main: fr.crafter.tickleman.RealShop.RealShopPlugin
version: 0.70
website: http://plugins.crafter.fr/tickleman/RealShop/
authors:
  - tickleman
commands:
  mny:
    description: RealEconomy money commands
  rs:
    description: RealShop chest-shop commands
  rshop:
    description: RealShop chest-shop commands
